[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "willutil_cpp"
version = "2.0.1"
requires-python = '>=3.9'
dependencies = [
    'numpy',
    'pytest',
]

