from glob import glob
from setuptools import setup, find_packages
from setuptools.command.install import install
from pybind11.setup_helpers import Pybind11Extension, ParallelCompile, build_ext, intree_extensions

# ext_modules = intree_extensions([
#     'willutil_cpp/bvh/bvh.cpp',
#     'willutil_cpp/bvh/bvh_test.cpp',
#     'willutil_cpp/bvh/bvh_nd.cpp',
#     'willutil_cpp/geom/miniball.cpp',
#     'willutil_cpp/geom/expand_xforms.cpp',
#     'willutil_cpp/geom/xform_dist.cpp',
#     'willutil_cpp/geom/bcc.cpp',
#     'willutil_cpp/geom/primitive_test.cpp',
#     'willutil_cpp/util/pybind_types_test.cpp',
#     'willutil_cpp/util/dilated_int_test.cpp',
#     'willutil_cpp/cluster/cookie_cutter.cpp',
#     'willutil_cpp/rms/qcptest.cpp',
#     'willutil_cpp/rms/qcp.cpp',
#     'willutil_cpp/phmap/phmap.cpp',
#     'willutil_cpp/xbin/xbin.cpp',
#     'willutil_cpp/xbin/xbin_test.cpp',
#     # # 'willutil_cpp/xbin/smear.cpp',
#     'willutil_cpp/xbin/xbin_util.cpp',
# ])
# for e in ext_modules:
#     e.include_dirs.append('.')
#     e.include_dirs.append('/usr/include')
#     e.include_dirs.append('willutil_cpp/extern')
#     # e.extra_compile_args += ['-w']
#     e.extra_compile_args += ['-std=c++17', '-O3', '-march=native', '-fPIC', '-w']

# ParallelCompile("NPY_NUM_BUILD_JOBS", default=8).install()

setup(
    name='willutil_cpp',
    version='0.2',
    url='https://github.com/willsheffler/willutil_cpp',
    author='Will Sheffler',
    author_email='willsheffler@gmail.com',
    description='Wrapped Cpp utils',
    packages=find_packages(include=['willutil_cpp', 'willutil_cpp.*']),
    test_suite='pytest',
    tests_require=['pytest'],
    setup_requires=['pybind11', 'numpy', 'icecream', 'cppimport'],
    install_requires=['pybind11', 'numpy', 'icecream', 'cppimport'],
    cmdclass={
        "build_ext": build_ext,
        'install': install
    },
    # ext_modules=ext_modules,
    package_data={
        'willutil_cpp': [
            'bvh/bvh.cpp',
            'bvh/bvh.hpp',
            'bvh/bvh_algo.hpp',
            'bvh/bvh_nd.cpp',
            'bvh/bvh_test.cpp',
            'cluster/cookie_cutter.cpp',
            'geom/bcc.cpp',
            'geom/bcc.hpp',
            'geom/expand_xforms.cpp',
            'geom/miniball.cpp',
            'geom/miniball.hpp',
            'geom/primitive.hpp',
            'geom/primitive_test.cpp',
            'geom/xform_dist.cpp',
            'phmap/phmap.cpp',
            'phmap/phmap.hpp',
            'rms/qcp.cpp',
            'rms/qcp.hpp',
            'rms/qcptest.cpp',
            'util/Timer.hpp',
            'util/assertions.hpp',
            'util/dilated_int.hpp',
            'util/dilated_int_test.cpp',
            'util/global_rng.hpp',
            'util/numeric.hpp',
            'util/pybind_types.hpp',
            'util/pybind_types_test.cpp',
            'util/str.hpp',
            'util/template_math.hpp',
            'util/types.hpp',
            'xbin/smear.cpp',
            'xbin/smear.hpp',
            'xbin/xbin.cpp',
            'xbin/xbin.hpp',
            'xbin/xbin_test.cpp',
            'xbin/xbin_util.cpp',
            'extern/miniball/Seb_debug.C',
            'extern/miniball/Seb-inl.h',
            'extern/miniball/Seb_point.h',
            'extern/miniball/Subspan-inl.h',
            'extern/miniball/Seb.h',
            'extern/miniball/Seb_configure.h',
            'extern/miniball/Seb_debug.h',
            'extern/miniball/Subspan.h',
            'extern/Eigen/StdList',
            'extern/Eigen/MetisSupport',
            'extern/Eigen/SparseLU',
            'extern/Eigen/CMakeLists.txt',
            'extern/Eigen/Core',
            'extern/Eigen/IterativeLinearSolvers',
            'extern/Eigen/SparseCholesky',
            'extern/Eigen/QtAlignedMalloc',
            'extern/Eigen/QR',
            'extern/Eigen/SparseCore',
            'extern/Eigen/PardisoSupport',
            'extern/Eigen/src/MetisSupport/MetisSupport.h',
            'extern/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h',
            'extern/Eigen/src/SparseLU/SparseLUImpl.h',
            'extern/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h',
            'extern/Eigen/src/SparseLU/SparseLU_Utils.h',
            'extern/Eigen/src/SparseLU/SparseLU_gemm_kernel.h',
            'extern/Eigen/src/SparseLU/SparseLU_pivotL.h',
            'extern/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h',
            'extern/Eigen/src/SparseLU/SparseLU_column_bmod.h',
            'extern/Eigen/src/SparseLU/SparseLU_Memory.h',
            'extern/Eigen/src/SparseLU/SparseLU.h',
            'extern/Eigen/src/SparseLU/SparseLU_Structs.h',
            'extern/Eigen/src/SparseLU/SparseLU_pruneL.h',
            'extern/Eigen/src/SparseLU/SparseLU_panel_dfs.h',
            'extern/Eigen/src/SparseLU/SparseLU_kernel_bmod.h',
            'extern/Eigen/src/SparseLU/SparseLU_relax_snode.h',
            'extern/Eigen/src/SparseLU/SparseLU_panel_bmod.h',
            'extern/Eigen/src/SparseLU/SparseLU_column_dfs.h',
            'extern/Eigen/src/Core/DiagonalProduct.h',
            'extern/Eigen/src/Core/MatrixBase.h',
            'extern/Eigen/src/Core/BandMatrix.h',
            'extern/Eigen/src/Core/PermutationMatrix.h',
            'extern/Eigen/src/Core/SelfCwiseBinaryOp.h',
            'extern/Eigen/src/Core/Assign.h',
            'extern/Eigen/src/Core/VectorBlock.h',
            'extern/Eigen/src/Core/Map.h',
            'extern/Eigen/src/Core/GlobalFunctions.h',
            'extern/Eigen/src/Core/VectorwiseOp.h',
            'extern/Eigen/src/Core/Select.h',
            'extern/Eigen/src/Core/AssignEvaluator.h',
            'extern/Eigen/src/Core/Replicate.h',
            'extern/Eigen/src/Core/MapBase.h',
            'extern/Eigen/src/Core/Matrix.h',
            'extern/Eigen/src/Core/NumTraits.h',
            'extern/Eigen/src/Core/Redux.h',
            'extern/Eigen/src/Core/NestByValue.h',
            'extern/Eigen/src/Core/MathFunctions.h',
            'extern/Eigen/src/Core/util/MKL_support.h',
            'extern/Eigen/src/Core/util/NonMPL2.h',
            'extern/Eigen/src/Core/util/DisableStupidWarnings.h',
            'extern/Eigen/src/Core/util/XprHelper.h',
            'extern/Eigen/src/Core/util/Macros.h',
            'extern/Eigen/src/Core/util/Meta.h',
            'extern/Eigen/src/Core/util/BlasUtil.h',
            'extern/Eigen/src/Core/util/StaticAssert.h',
            'extern/Eigen/src/Core/util/Memory.h',
            'extern/Eigen/src/Core/util/Constants.h',
            'extern/Eigen/src/Core/util/ForwardDeclarations.h',
            'extern/Eigen/src/Core/util/ReenableStupidWarnings.h',
            'extern/Eigen/src/Core/Visitor.h',
            'extern/Eigen/src/Core/MathFunctionsImpl.h',
            'extern/Eigen/src/Core/SolverBase.h',
            'extern/Eigen/src/Core/CwiseBinaryOp.h',
            'extern/Eigen/src/Core/ReturnByValue.h',
            'extern/Eigen/src/Core/functors/NullaryFunctors.h',
            'extern/Eigen/src/Core/functors/TernaryFunctors.h',
            'extern/Eigen/src/Core/functors/UnaryFunctors.h',
            'extern/Eigen/src/Core/functors/AssignmentFunctors.h',
            'extern/Eigen/src/Core/functors/StlFunctors.h',
            'extern/Eigen/src/Core/functors/BinaryFunctors.h',
            'extern/Eigen/src/Core/DenseStorage.h',
            'extern/Eigen/src/Core/Stride.h',
            'extern/Eigen/src/Core/Transpose.h',
            'extern/Eigen/src/Core/GenericPacketMath.h',
            'extern/Eigen/src/Core/ProductEvaluators.h',
            'extern/Eigen/src/Core/CwiseUnaryOp.h',
            'extern/Eigen/src/Core/SolveTriangular.h',
            'extern/Eigen/src/Core/IO.h',
            'extern/Eigen/src/Core/EigenBase.h',
            'extern/Eigen/src/Core/DiagonalMatrix.h',
            'extern/Eigen/src/Core/StableNorm.h',
            'extern/Eigen/src/Core/CwiseNullaryOp.h',
            'extern/Eigen/src/Core/Random.h',
            'extern/Eigen/src/Core/Fuzzy.h',
            'extern/Eigen/src/Core/TriangularMatrix.h',
            'extern/Eigen/src/Core/GeneralProduct.h',
            'extern/Eigen/src/Core/DenseBase.h',
            'extern/Eigen/src/Core/Diagonal.h',
            'extern/Eigen/src/Core/CommaInitializer.h',
            'extern/Eigen/src/Core/SelfAdjointView.h',
            'extern/Eigen/src/Core/Inverse.h',
            'extern/Eigen/src/Core/products/TriangularSolverVector.h',
            'extern/Eigen/src/Core/products/GeneralBlockPanelKernel.h',
            'extern/Eigen/src/Core/products/TriangularSolverMatrix.h',
            'extern/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h',
            'extern/Eigen/src/Core/products/SelfadjointProduct.h',
            'extern/Eigen/src/Core/products/Parallelizer.h',
            'extern/Eigen/src/Core/products/GeneralMatrixVector.h',
            'extern/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h',
            'extern/Eigen/src/Core/products/TriangularMatrixVector.h',
            'extern/Eigen/src/Core/products/SelfadjointMatrixVector.h',
            'extern/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h',
            'extern/Eigen/src/Core/products/SelfadjointRank2Update.h',
            'extern/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h',
            'extern/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h',
            'extern/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h',
            'extern/Eigen/src/Core/products/TriangularMatrixMatrix.h',
            'extern/Eigen/src/Core/products/SelfadjointMatrixMatrix.h',
            'extern/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h',
            'extern/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h',
            'extern/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h',
            'extern/Eigen/src/Core/products/GeneralMatrixMatrix.h',
            'extern/Eigen/src/Core/PlainObjectBase.h',
            'extern/Eigen/src/Core/Solve.h',
            'extern/Eigen/src/Core/BooleanRedux.h',
            'extern/Eigen/src/Core/Transpositions.h',
            'extern/Eigen/src/Core/ForceAlignedAccess.h',
            'extern/Eigen/src/Core/Assign_MKL.h',
            'extern/Eigen/src/Core/ConditionEstimator.h',
            'extern/Eigen/src/Core/Product.h',
            'extern/Eigen/src/Core/Array.h',
            'extern/Eigen/src/Core/NoAlias.h',
            'extern/Eigen/src/Core/Dot.h',
            'extern/Eigen/src/Core/Ref.h',
            'extern/Eigen/src/Core/Swap.h',
            'extern/Eigen/src/Core/DenseCoeffsBase.h',
            'extern/Eigen/src/Core/CoreIterators.h',
            'extern/Eigen/src/Core/CoreEvaluators.h',
            'extern/Eigen/src/Core/arch/AVX512/MathFunctions.h',
            'extern/Eigen/src/Core/arch/AVX512/PacketMath.h',
            'extern/Eigen/src/Core/arch/NEON/Complex.h',
            'extern/Eigen/src/Core/arch/NEON/MathFunctions.h',
            'extern/Eigen/src/Core/arch/NEON/PacketMath.h',
            'extern/Eigen/src/Core/arch/AVX/Complex.h',
            'extern/Eigen/src/Core/arch/AVX/MathFunctions.h',
            'extern/Eigen/src/Core/arch/AVX/PacketMath.h',
            'extern/Eigen/src/Core/arch/AVX/TypeCasting.h',
            'extern/Eigen/src/Core/arch/CUDA/Half.h',
            'extern/Eigen/src/Core/arch/CUDA/Complex.h',
            'extern/Eigen/src/Core/arch/CUDA/MathFunctions.h',
            'extern/Eigen/src/Core/arch/CUDA/PacketMathHalf.h',
            'extern/Eigen/src/Core/arch/CUDA/PacketMath.h',
            'extern/Eigen/src/Core/arch/CUDA/TypeCasting.h',
            'extern/Eigen/src/Core/arch/SSE/Complex.h',
            'extern/Eigen/src/Core/arch/SSE/MathFunctions.h',
            'extern/Eigen/src/Core/arch/SSE/PacketMath.h',
            'extern/Eigen/src/Core/arch/SSE/TypeCasting.h',
            'extern/Eigen/src/Core/arch/ZVector/Complex.h',
            'extern/Eigen/src/Core/arch/ZVector/MathFunctions.h',
            'extern/Eigen/src/Core/arch/ZVector/PacketMath.h',
            'extern/Eigen/src/Core/arch/AltiVec/Complex.h',
            'extern/Eigen/src/Core/arch/AltiVec/MathFunctions.h',
            'extern/Eigen/src/Core/arch/AltiVec/PacketMath.h',
            'extern/Eigen/src/Core/arch/Default/Settings.h',
            'extern/Eigen/src/Core/Block.h',
            'extern/Eigen/src/Core/ArrayBase.h',
            'extern/Eigen/src/Core/Reverse.h',
            'extern/Eigen/src/Core/CwiseUnaryView.h',
            'extern/Eigen/src/Core/CwiseTernaryOp.h',
            'extern/Eigen/src/Core/ArrayWrapper.h',
            'extern/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h',
            'extern/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h',
            'extern/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h',
            'extern/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h',
            'extern/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h',
            'extern/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h',
            'extern/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h',
            'extern/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h',
            'extern/Eigen/src/SparseCholesky/SimplicialCholesky.h',
            'extern/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h',
            'extern/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h',
            'extern/Eigen/src/QR/HouseholderQR_LAPACKE.h',
            'extern/Eigen/src/QR/ColPivHouseholderQR.h',
            'extern/Eigen/src/QR/HouseholderQR.h',
            'extern/Eigen/src/QR/FullPivHouseholderQR.h',
            'extern/Eigen/src/QR/CompleteOrthogonalDecomposition.h',
            'extern/Eigen/src/SparseCore/SparseUtil.h',
            'extern/Eigen/src/SparseCore/SparseCwiseBinaryOp.h',
            'extern/Eigen/src/SparseCore/SparseFuzzy.h',
            'extern/Eigen/src/SparseCore/SparseColEtree.h',
            'extern/Eigen/src/SparseCore/AmbiVector.h',
            'extern/Eigen/src/SparseCore/SparseView.h',
            'extern/Eigen/src/SparseCore/SparseSolverBase.h',
            'extern/Eigen/src/SparseCore/SparseCwiseUnaryOp.h',
            'extern/Eigen/src/SparseCore/SparseMap.h',
            'extern/Eigen/src/SparseCore/SparseProduct.h',
            'extern/Eigen/src/SparseCore/SparseDenseProduct.h',
            'extern/Eigen/src/SparseCore/SparseRef.h',
            'extern/Eigen/src/SparseCore/SparseSparseProductWithPruning.h',
            'extern/Eigen/src/SparseCore/CompressedStorage.h',
            'extern/Eigen/src/SparseCore/SparseTriangularView.h',
            'extern/Eigen/src/SparseCore/TriangularSolver.h',
            'extern/Eigen/src/SparseCore/SparseDot.h',
            'extern/Eigen/src/SparseCore/SparseTranspose.h',
            'extern/Eigen/src/SparseCore/SparsePermutation.h',
            'extern/Eigen/src/SparseCore/SparseAssign.h',
            'extern/Eigen/src/SparseCore/MappedSparseMatrix.h',
            'extern/Eigen/src/SparseCore/SparseRedux.h',
            'extern/Eigen/src/SparseCore/SparseVector.h',
            'extern/Eigen/src/SparseCore/SparseBlock.h',
            'extern/Eigen/src/SparseCore/SparseSelfAdjointView.h',
            'extern/Eigen/src/SparseCore/SparseDiagonalProduct.h',
            'extern/Eigen/src/SparseCore/SparseMatrix.h',
            'extern/Eigen/src/SparseCore/SparseCompressedBase.h',
            'extern/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h',
            'extern/Eigen/src/SparseCore/SparseMatrixBase.h',
            'extern/Eigen/src/PardisoSupport/PardisoSupport.h',
            'extern/Eigen/src/Jacobi/Jacobi.h',
            'extern/Eigen/src/misc/RealSvd2x2.h',
            'extern/Eigen/src/misc/Image.h',
            'extern/Eigen/src/misc/Kernel.h',
            'extern/Eigen/src/misc/lapacke_mangling.h',
            'extern/Eigen/src/misc/lapacke.h',
            'extern/Eigen/src/misc/lapack.h',
            'extern/Eigen/src/misc/blas.h',
            'extern/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h',
            'extern/Eigen/src/Cholesky/LLT_LAPACKE.h',
            'extern/Eigen/src/Cholesky/LLT.h',
            'extern/Eigen/src/Cholesky/LDLT.h',
            'extern/Eigen/src/StlSupport/StdList.h',
            'extern/Eigen/src/StlSupport/StdDeque.h',
            'extern/Eigen/src/StlSupport/StdVector.h',
            'extern/Eigen/src/StlSupport/details.h',
            'extern/Eigen/src/Eigenvalues/ComplexEigenSolver.h',
            'extern/Eigen/src/Eigenvalues/ComplexSchur.h',
            'extern/Eigen/src/Eigenvalues/RealQZ.h',
            'extern/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h',
            'extern/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h',
            'extern/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h',
            'extern/Eigen/src/Eigenvalues/EigenSolver.h',
            'extern/Eigen/src/Eigenvalues/RealSchur.h',
            'extern/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h',
            'extern/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h',
            'extern/Eigen/src/Eigenvalues/Tridiagonalization.h',
            'extern/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h',
            'extern/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h',
            'extern/Eigen/src/Eigenvalues/HessenbergDecomposition.h',
            'extern/Eigen/src/OrderingMethods/Amd.h',
            'extern/Eigen/src/OrderingMethods/Ordering.h',
            'extern/Eigen/src/OrderingMethods/Eigen_Colamd.h',
            'extern/Eigen/src/Householder/BlockHouseholder.h',
            'extern/Eigen/src/Householder/HouseholderSequence.h',
            'extern/Eigen/src/Householder/Householder.h',
            'extern/Eigen/src/SparseQR/SparseQR.h',
            'extern/Eigen/src/plugins/ArrayCwiseBinaryOps.h',
            'extern/Eigen/src/plugins/MatrixCwiseBinaryOps.h',
            'extern/Eigen/src/plugins/MatrixCwiseUnaryOps.h',
            'extern/Eigen/src/plugins/BlockMethods.h',
            'extern/Eigen/src/plugins/ArrayCwiseUnaryOps.h',
            'extern/Eigen/src/plugins/CommonCwiseBinaryOps.h',
            'extern/Eigen/src/plugins/CommonCwiseUnaryOps.h',
            'extern/Eigen/src/SuperLUSupport/SuperLUSupport.h',
            'extern/Eigen/src/Geometry/Umeyama.h',
            'extern/Eigen/src/Geometry/Translation.h',
            'extern/Eigen/src/Geometry/Transform.h',
            'extern/Eigen/src/Geometry/Homogeneous.h',
            'extern/Eigen/src/Geometry/RotationBase.h',
            'extern/Eigen/src/Geometry/AlignedBox.h',
            'extern/Eigen/src/Geometry/OrthoMethods.h',
            'extern/Eigen/src/Geometry/Hyperplane.h',
            'extern/Eigen/src/Geometry/Scaling.h',
            'extern/Eigen/src/Geometry/AngleAxis.h',
            'extern/Eigen/src/Geometry/Rotation2D.h',
            'extern/Eigen/src/Geometry/arch/Geometry_SSE.h',
            'extern/Eigen/src/Geometry/Quaternion.h',
            'extern/Eigen/src/Geometry/EulerAngles.h',
            'extern/Eigen/src/Geometry/ParametrizedLine.h',
            'extern/Eigen/src/CholmodSupport/CholmodSupport.h',
            'extern/Eigen/src/SVD/JacobiSVD_LAPACKE.h',
            'extern/Eigen/src/SVD/BDCSVD.h',
            'extern/Eigen/src/SVD/SVDBase.h',
            'extern/Eigen/src/SVD/UpperBidiagonalization.h',
            'extern/Eigen/src/SVD/JacobiSVD.h',
            'extern/Eigen/src/LU/FullPivLU.h',
            'extern/Eigen/src/LU/PartialPivLU_LAPACKE.h',
            'extern/Eigen/src/LU/PartialPivLU.h',
            'extern/Eigen/src/LU/Determinant.h',
            'extern/Eigen/src/LU/InverseImpl.h',
            'extern/Eigen/src/LU/arch/Inverse_SSE.h',
            'extern/Eigen/src/UmfPackSupport/UmfPackSupport.h',
            'extern/Eigen/src/PaStiXSupport/PaStiXSupport.h',
            'extern/Eigen/Jacobi',
            'extern/Eigen/SPQRSupport',
            'extern/Eigen/Eigen',
            'extern/Eigen/Cholesky',
            'extern/Eigen/StdDeque',
            'extern/Eigen/Eigenvalues',
            'extern/Eigen/OrderingMethods',
            'extern/Eigen/Householder',
            'extern/Eigen/SparseQR',
            'extern/Eigen/StdVector',
            'extern/Eigen/SuperLUSupport',
            'extern/Eigen/Geometry',
            'extern/Eigen/CholmodSupport',
            'extern/Eigen/Dense',
            'extern/Eigen/SVD',
            'extern/Eigen/Sparse',
            'extern/Eigen/LU',
            'extern/Eigen/UmfPackSupport',
            'extern/Eigen/PaStiXSupport',
            'extern/parallel_hashmap/phmap.h',
            'extern/parallel_hashmap/phmap_fwd_decl.h',
            'extern/parallel_hashmap/phmap_bits.h',
            'extern/parallel_hashmap/phmap_config.h',
            'extern/parallel_hashmap/meminfo.h',
            'extern/parallel_hashmap/phmap_base.h',
            'extern/parallel_hashmap/phmap_utils.h',
        ]
    })
